name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

env:
  # Any version upgrades should be done here
  OSQUERY_VERSION: 5.14.1
  KUBECTL_VERSION: 1.31.3
  EXTENSION_VERSION: 1.2.0

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Extract tagged Agent Docker Image version
        id: image-version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Debug - tag extraction
        run: echo "Using transformed tag ${{ steps.image-version.outputs.version }}"

      - name: Versions used for the build
        run: |
          echo "DOCKER_VERSION=${{ steps.image-version.outputs.version }}"
          echo "OSQUERY_VERSION=${{ env.OSQUERY_VERSION }}"
          echo "KUBECTL_VERSION=${{ env.KUBECTL_VERSION }}"
          echo "EXTENSION_VERSION=${{ env.EXTENSION_VERSION }}"

      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push GitHub Container Registry
        id: docker_build
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: ./kubernetes/docker
          push: true
          platforms: linux/arm64,linux/amd64
          tags: |
            ghcr.io/turbot/guardrails-agent-kubernetes:${{ steps.image-version.outputs.version }}
            ghcr.io/turbot/guardrails-agent-kubernetes:latest
          build-args: |
            OSQUERY_VERSION=${{ env.OSQUERY_VERSION }}
            KUBECTL_VERSION=${{ env.KUBECTL_VERSION }}
            EXTENSION_VERSION=${{ env.EXTENSION_VERSION }}
